#!/usr/bin/env python3
"""
OpenCode integration for AI BGM.

OpenCode does not support declarative lifecycle hooks in its config.
Instead, it provides a plugin system (JS/TS modules) that can subscribe
to events. This integration generates a lightweight JS plugin file.
"""

import shutil
from pathlib import Path
from typing import Tuple

from mythril_agent_bgm.commands.integrations import AIToolIntegration


class OpenCodeIntegration(AIToolIntegration):
    """Integration for OpenCode via plugin file."""

    def get_tool_info(self) -> Tuple[str, str]:
        """Get OpenCode tool information."""
        return ("opencode", "OpenCode")

    def get_settings_path(self) -> Path:
        """Get the plugin file path."""
        return Path.home() / ".config" / "opencode" / "plugins" / "opencode-bgm.js"

    def get_config_dir(self) -> Path:
        """OpenCode config root is ~/.config/opencode/, not the plugins/ subdirectory."""
        return Path.home() / ".config" / "opencode"

    def setup_hooks(self, settings: dict) -> dict:
        """Not used for OpenCode (plugin-based setup). Returns settings unchanged."""
        return settings

    def cleanup_hooks(self, settings: dict) -> dict:
        """Not used for OpenCode (plugin-based cleanup). Returns settings unchanged."""
        return settings

    def perform_setup(self) -> Tuple[bool, str]:
        """Write the BGM plugin JS file into OpenCode's plugin directory."""
        config_dir = self.get_config_dir()
        if not config_dir.exists():
            return (False, f"OpenCode: Config directory not found ({config_dir})")

        bgm_path = shutil.which("bgm")
        if not bgm_path:
            return (False, "OpenCode: 'bgm' command not found in PATH")

        plugin_dir = self.get_settings_path().parent
        plugin_dir.mkdir(parents=True, exist_ok=True)

        plugin_content = self._generate_plugin(bgm_path)
        self.get_settings_path().write_text(plugin_content, encoding="utf-8")
        return (True, "OpenCode: Plugin installed successfully [OK]")

    def perform_cleanup(self) -> Tuple[bool, str]:
        """Remove the BGM plugin JS file from OpenCode's plugin directory."""
        plugin_path = self.get_settings_path()
        if not plugin_path.exists():
            return (True, "OpenCode: No plugin file found, nothing to clean up")

        plugin_path.unlink()
        return (True, "OpenCode: Plugin removed successfully [OK]")

    @staticmethod
    def _generate_plugin(bgm_path: str) -> str:
        """Generate the plugin JS content with the resolved bgm path.

        Uses Bun.spawn instead of Bun's $ template literal because
        $ misparses compound command strings (e.g. "$`${path} play work 0`"
        passes incorrect arguments to the subprocess).
        """
        return (
            "// Auto-generated by AI BGM (https://github.com/anthropics/mythril-agent-bgm)\n"
            "// Re-run `bgm setup` to regenerate.\n"
            "\n"
            "export const BGMPlugin = async () => {\n"
            "  let currentSessionID = null;\n"
            "  let isWorking = false;\n"
            "  let lastIdleTime = 0;\n"
            "  let isWaitingInput = false;\n"
            "\n"
            "  const DEBOUNCE_MS = 2000;\n"
            f'  const BGM = "{bgm_path}";\n'
            "\n"
            "  const runBgm = (...args) => {\n"
            '    Bun.spawn([BGM, ...args], { stdout: "ignore", env: process.env });\n'
            "  };\n"
            "\n"
            "  return {\n"
            "    event: async ({ event }) => {\n"
            "      const props = event.properties;\n"
            "\n"
            "      switch (event.type) {\n"
            '        case "session.created":\n'
            "          currentSessionID = props?.info?.id ?? null;\n"
            "          isWorking = false;\n"
            "          lastIdleTime = 0;\n"
            "          isWaitingInput = false;\n"
            "          break;\n"
            "\n"
            '        case "message.updated":\n'
            "          if (\n"
            "            !isWorking &&\n"
            '            props?.info?.role === "user" &&\n'
            "            Date.now() - lastIdleTime > DEBOUNCE_MS\n"
            "          ) {\n"
            "            isWaitingInput = false;\n"
            "            isWorking = true;\n"
            '            runBgm("play", "work", "0");\n'
            "          }\n"
            "          break;\n"
            "\n"
            '        case "permission.asked":\n'
            "          isWaitingInput = true;\n"
            '          runBgm("play", "notification", "0");\n'
            "          break;\n"
            "\n"
            '        case "permission.replied":\n'
            "          if (isWaitingInput) {\n"
            "            isWaitingInput = false;\n"
            "            isWorking = true;\n"
            '            runBgm("play", "work", "0");\n'
            "          }\n"
            "          break;\n"
            "\n"
            '        case "session.idle":\n'
            "          if (isWorking) {\n"
            "            isWorking = false;\n"
            "            lastIdleTime = Date.now();\n"
            '            runBgm("play", "done");\n'
            "          }\n"
            "          break;\n"
            "\n"
            '        case "session.deleted":\n'
            "          isWorking = false;\n"
            "          isWaitingInput = false;\n"
            '          runBgm("stop");\n'
            "          currentSessionID = null;\n"
            "          break;\n"
            "      }\n"
            "    },\n"
            "\n"
            '    "tool.execute.before": async (input) => {\n'
            '      if (input.tool === "question") {\n'
            "        isWaitingInput = true;\n"
            "        isWorking = false;\n"
            '        runBgm("play", "notification", "0");\n'
            "      }\n"
            "    },\n"
            "  };\n"
            "};\n"
            "\n"
            "export default BGMPlugin;\n"
        )
