#!/usr/bin/env python3
"""Tests for the Pi Coding Agent (pi) AI tool integration."""

import shutil
import subprocess
from pathlib import Path
from unittest import mock

import pytest

from mythril_agent_bgm.commands.integrations.pi import PiIntegration
from mythril_agent_bgm.commands.integrations.registry import IntegrationRegistry


@pytest.fixture
def fake_home(tmp_path: Path) -> Path:
    """A fake home directory with a .pi/agent config root."""
    agent_dir = tmp_path / ".pi" / "agent"
    agent_dir.mkdir(parents=True)
    return tmp_path


def _make_bgm(home: Path) -> Path:
    """Create a fake bgm executable inside the fake home."""
    fake_bgm = home / "fake-bgm"
    fake_bgm.write_text("#!/bin/sh\necho ok\n", encoding="utf-8")
    fake_bgm.chmod(0o755)
    return fake_bgm


@pytest.fixture
def patched_home(fake_home: Path):
    return mock.patch(
        "mythril_agent_bgm.commands.integrations.pi.Path.home",
        return_value=fake_home,
    )


def test_tool_info():
    assert PiIntegration().get_tool_info() == ("pi", "Pi Coding Agent")


def test_settings_path_under_pi_extensions(patched_home):
    with patched_home:
        assert PiIntegration().get_settings_path() == (
            Path.home() / ".pi" / "agent" / "extensions" / "mythril-agent-bgm.ts"
        )


def test_config_dir_is_pi_agent(patched_home):
    with patched_home:
        assert PiIntegration().get_config_dir() == Path.home() / ".pi" / "agent"


def test_generate_extension_contains_expected_pieces():
    ext = PiIntegration._generate_extension("/x/bgm")
    # Header comment: auto-generated marker (canonical repo URL) + hint.
    assert "Auto-generated by AI BGM" in ext
    assert "https://github.com/jie-meng/mythril-agent-bgm" in ext
    assert "Re-run `bgm setup` to regenerate." in ext
    # Plain-JS-compatible ESM: no TS type annotations, types via JSDoc only.
    assert 'import { spawn } from "node:child_process";' in ext
    assert 'const BGM = "/x/bgm";' in ext
    assert "export default function (pi)" in ext
    assert '@param {import("@earendil-works/pi-coding-agent").ExtensionAPI} pi' in ext
    # The five event handlers.
    assert 'pi.on("agent_start"' in ext
    assert 'pi.on("agent_end"' in ext
    assert 'pi.on("tool_call"' in ext
    assert 'pi.on("tool_result"' in ext
    assert 'pi.on("session_shutdown"' in ext
    # BGM commands.
    assert 'run("play", "work", "0")' in ext
    assert 'run("play", "done")' in ext
    assert 'run("play", "notification", "0")' in ext
    assert 'run("stop")' in ext
    # spawn configuration: detached + windowsHide, errors swallowed.
    assert 'stdio: "ignore"' in ext
    assert "detached: true" in ext
    assert "windowsHide: true" in ext
    assert 'child.on("error", () => {})' in ext
    assert "child.unref()" in ext
    # Work/done gating and question bookkeeping.
    assert "let lastWorkTime = 0;" in ext
    assert "const pendingQuestions = new Set();" in ext
    assert "lastWorkTime > 0" in ext
    assert "pendingQuestions.add(event.toolCallId)" in ext
    assert "pendingQuestions.delete(event.toolCallId)" in ext
    assert "pendingQuestions.clear()" in ext
    # Conservative question/ask tool-name matching. Optional chaining guards
    # against a missing toolName: an undefined field must never throw a
    # TypeError into the pi process.
    assert 'event.toolName === "question"' in ext
    assert 'event.toolName?.startsWith("ask")' in ext
    assert 'event.toolName.startsWith("ask")' not in ext


def test_generate_extension_event_mapping():
    ext = PiIntegration._generate_extension("/x/bgm")
    # agent_start drives work and records the timestamp.
    start_block = ext[ext.index('pi.on("agent_start"') : ext.index('pi.on("agent_end"')]
    assert "lastWorkTime = Date.now()" in start_block
    assert 'run("play", "work", "0")' in start_block
    # agent_end gates the done cue on work music having actually played.
    end_block = ext[ext.index('pi.on("agent_end"') : ext.index('pi.on("tool_call"')]
    assert "lastWorkTime > 0" in end_block
    assert 'run("play", "done")' in end_block
    assert 'run("play", "work", "0")' not in end_block
    # tool_call -> notification, pendingQuestions add, work marker reset.
    call_block = ext[ext.index('pi.on("tool_call"') : ext.index('pi.on("tool_result"')]
    assert "pendingQuestions.add(event.toolCallId)" in call_block
    assert "lastWorkTime = 0" in call_block
    assert 'run("play", "notification", "0")' in call_block
    # tool_result -> resume work only when the callId was pending.
    result_block = ext[ext.index('pi.on("tool_result"') : ext.index('pi.on("session_shutdown"')]
    assert "pendingQuestions.delete(event.toolCallId)" in result_block
    assert "lastWorkTime = Date.now()" in result_block
    assert 'run("play", "work", "0")' in result_block
    # session_shutdown clears bookkeeping first, then stops the music.
    shutdown_block = ext[ext.index('pi.on("session_shutdown"') :]
    assert "pendingQuestions.clear()" in shutdown_block
    assert "lastWorkTime = 0" in shutdown_block
    assert 'run("stop")' in shutdown_block


def test_generate_extension_embeds_windows_bgm_path():
    # JSON-escaped backslashes must stay valid inside the generated JS.
    ext = PiIntegration._generate_extension(r"C:\tools\bgm.exe")
    assert r'"C:\\tools\\bgm.exe"' in ext


def test_generate_extension_embeds_quoted_bgm_path():
    # JSON-escaped quotes (and backslashes) must stay valid inside the JS.
    ext = PiIntegration._generate_extension(r'C:\tools\bgm "x".exe')
    assert r'"C:\\tools\\bgm \"x\".exe"' in ext


def test_generated_extension_passes_node_syntax_check(tmp_path: Path):
    # The generated extension must be plain-JS-compatible ESM so pi's jiti
    # loader accepts it; `node --check` verifies the syntax exactly as it
    # would be loaded from ~/.pi/agent/extensions/. Skipped when node is not
    # available on this machine.
    node = shutil.which("node")
    if node is None:
        pytest.skip("node not available on this machine — skipping syntax check")
    extension = tmp_path / "mythril-agent-bgm.ts"
    extension.write_text(PiIntegration._generate_extension("/x/bgm"), encoding="utf-8")
    result = subprocess.run(
        [node, "--check", str(extension)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr


def test_setup_cleanup_roundtrip(fake_home: Path, patched_home):
    fake_bgm = _make_bgm(fake_home)
    with patched_home:
        with mock.patch("shutil.which", return_value=str(fake_bgm)):
            integration = PiIntegration()
            assert not integration.is_configured()

            ok, _ = integration.perform_setup()
            assert ok
            assert integration.is_configured()
            assert integration.is_up_to_date()
            assert integration.get_settings_path().exists()

            ok, _ = integration.perform_cleanup()
            assert ok
            assert not integration.is_configured()
            assert not integration.get_settings_path().exists()


def test_setup_cleanup_idempotent(fake_home: Path, patched_home):
    fake_bgm = _make_bgm(fake_home)
    with patched_home:
        with mock.patch("shutil.which", return_value=str(fake_bgm)):
            integration = PiIntegration()
            ok, _ = integration.perform_setup()
            assert ok
            extension = integration.get_settings_path()
            first = extension.read_text(encoding="utf-8")
            assert not list(extension.parent.glob("mythril-agent-bgm.ts.*.bak"))

            # Repeated setup with identical content: no rewrite, no backup.
            ok, _ = integration.perform_setup()
            assert ok
            assert extension.read_text(encoding="utf-8") == first
            assert not list(extension.parent.glob("mythril-agent-bgm.ts.*.bak"))

            ok, _ = integration.perform_cleanup()
            assert ok
            assert not extension.exists()
            # Repeated cleanup: file already gone, still a success.
            ok, message = integration.perform_cleanup()
            assert ok
            assert "nothing to clean up" in message


def test_cleanup_removes_only_own_file(fake_home: Path, patched_home):
    fake_bgm = _make_bgm(fake_home)
    ext_dir = fake_home / ".pi" / "agent" / "extensions"
    ext_dir.mkdir(parents=True)
    other = ext_dir / "other-extension.ts"
    other.write_text("export default function (pi) {}\n", encoding="utf-8")
    with patched_home:
        with mock.patch("shutil.which", return_value=str(fake_bgm)):
            integration = PiIntegration()
            ok, _ = integration.perform_setup()
            assert ok
            ok, _ = integration.perform_cleanup()
            assert ok
            # Must be checked inside the patched home — outside it, this reads
            # the developer's real ~/.pi extension and fails on any machine
            # where bgm is actually hooked into pi.
            assert not integration.get_settings_path().exists()
    assert other.exists()
    assert other.read_text(encoding="utf-8") == "export default function (pi) {}\n"


def test_cleanup_unlinks_symlink(fake_home: Path, patched_home):
    # A symlinked extension must be unlinked (rmtree on a symlink raises
    # OSError) and the target must be left untouched.
    target = fake_home / "real-extension.ts"
    target.write_text("export default function (pi) {}\n", encoding="utf-8")
    ext_dir = fake_home / ".pi" / "agent" / "extensions"
    ext_dir.mkdir(parents=True)
    link = ext_dir / "mythril-agent-bgm.ts"
    try:
        link.symlink_to(target)
    except OSError:
        pytest.skip("symlinks not supported on this platform")
    with patched_home:
        ok, _ = PiIntegration().perform_cleanup()
        assert ok
    assert not link.exists()
    assert target.exists()


def test_setup_backs_up_existing_different_file(fake_home: Path, patched_home):
    fake_bgm = _make_bgm(fake_home)
    ext_dir = fake_home / ".pi" / "agent" / "extensions"
    ext_dir.mkdir(parents=True)
    extension = ext_dir / "mythril-agent-bgm.ts"
    user_content = "// user custom extension\n"
    extension.write_text(user_content, encoding="utf-8")
    with patched_home:
        with mock.patch("shutil.which", return_value=str(fake_bgm)):
            ok, _ = PiIntegration().perform_setup()
            assert ok
    backups = list(ext_dir.glob("mythril-agent-bgm.ts.*.bak"))
    assert len(backups) == 1
    assert backups[0].read_text(encoding="utf-8") == user_content
    assert "Auto-generated by AI BGM" in extension.read_text(encoding="utf-8")


def test_setup_backs_up_with_unique_timestamped_names(fake_home: Path, patched_home):
    # Two consecutive setups with different existing content must both succeed
    # and produce DISTINCT backups (a fixed ".bak" name would collide:
    # FileExistsError on Windows, silent overwrite of the previous backup on
    # POSIX — exactly the "bgm path changed, re-run setup" scenario).
    fake_bgm = _make_bgm(fake_home)
    ext_dir = fake_home / ".pi" / "agent" / "extensions"
    ext_dir.mkdir(parents=True)
    extension = ext_dir / "mythril-agent-bgm.ts"
    extension.write_text("// first user version\n", encoding="utf-8")
    with patched_home:
        with mock.patch("shutil.which", return_value=str(fake_bgm)):
            integration = PiIntegration()
            ok, _ = integration.perform_setup()
            assert ok
            generated = extension.read_text(encoding="utf-8")
            # Second setup sees a different existing file again (e.g. a user
            # edit after the first install).
            extension.write_text(generated + "\n// tampered\n", encoding="utf-8")
            ok, _ = integration.perform_setup()
            assert ok
            assert extension.read_text(encoding="utf-8") == generated
    backups = list(ext_dir.glob("mythril-agent-bgm.ts.*.bak"))
    assert len(backups) == 2
    assert len({backup.name for backup in backups}) == 2
    assert {backup.read_text(encoding="utf-8") for backup in backups} == {
        "// first user version\n",
        generated + "\n// tampered\n",
    }


def test_configured_and_up_to_date_combinations(fake_home: Path, patched_home):
    fake_bgm = _make_bgm(fake_home)
    with patched_home:
        with mock.patch("shutil.which", return_value=str(fake_bgm)):
            integration = PiIntegration()
            # (missing): not configured, not up to date.
            assert not integration.is_configured()
            assert not integration.is_up_to_date()

            ok, _ = integration.perform_setup()
            assert ok
            # (exists, matching): configured and up to date.
            assert integration.is_configured()
            assert integration.is_up_to_date()

            # (exists, different): configured but not up to date.
            extension = integration.get_settings_path()
            extension.write_text(
                extension.read_text(encoding="utf-8") + "\n// tampered\n", encoding="utf-8"
            )
            assert integration.is_configured()
            assert not integration.is_up_to_date()

            ok, _ = integration.perform_cleanup()
            assert ok
            # (missing again): not configured, not up to date.
            assert not integration.is_configured()
            assert not integration.is_up_to_date()


def test_up_to_date_false_after_bgm_path_change(fake_home: Path, patched_home):
    fake_bgm = _make_bgm(fake_home)
    other_bgm = fake_home / "other-bgm"
    other_bgm.write_text("#!/bin/sh\necho ok\n", encoding="utf-8")
    other_bgm.chmod(0o755)
    with patched_home:
        with mock.patch("shutil.which", return_value=str(fake_bgm)):
            integration = PiIntegration()
            ok, _ = integration.perform_setup()
            assert ok
            assert integration.is_up_to_date()
        # bgm moved: embedded path no longer matches generated content.
        with mock.patch("shutil.which", return_value=str(other_bgm)):
            assert not integration.is_up_to_date()


def test_read_failure_falls_back(fake_home: Path, patched_home):
    # An unreadable extension file must degrade to False instead of raising
    # through the curses UI (mock keeps this Windows-safe).
    fake_bgm = _make_bgm(fake_home)
    with patched_home:
        with mock.patch("shutil.which", return_value=str(fake_bgm)):
            integration = PiIntegration()
            ok, _ = integration.perform_setup()
            assert ok
            with mock.patch.object(Path, "read_text", side_effect=OSError("permission denied")):
                assert not integration.is_up_to_date()


def test_setup_write_failure_falls_back(fake_home: Path, patched_home):
    fake_bgm = _make_bgm(fake_home)
    with patched_home:
        with mock.patch("shutil.which", return_value=str(fake_bgm)):
            integration = PiIntegration()
            with mock.patch.object(Path, "write_text", side_effect=OSError("permission denied")):
                ok, message = integration.perform_setup()
                assert not ok
                assert "Unable to write extension" in message


def test_cleanup_failure_falls_back(fake_home: Path, patched_home):
    fake_bgm = _make_bgm(fake_home)
    with patched_home:
        with mock.patch("shutil.which", return_value=str(fake_bgm)):
            integration = PiIntegration()
            ok, _ = integration.perform_setup()
            assert ok
            with mock.patch.object(Path, "unlink", side_effect=OSError("permission denied")):
                ok, message = integration.perform_cleanup()
                assert not ok
                assert "Unable to remove extension" in message


def test_setup_requires_config_dir(tmp_path: Path):
    # No ~/.pi/agent dir -> setup reports failure with an initialization hint.
    with mock.patch("mythril_agent_bgm.commands.integrations.pi.Path.home", return_value=tmp_path):
        ok, message = PiIntegration().perform_setup()
        assert not ok
        assert "Config directory not found" in message
        assert "run `pi` once to initialize" in message


def test_setup_requires_bgm(fake_home: Path, patched_home):
    with patched_home:
        with mock.patch("shutil.which", return_value=None):
            ok, message = PiIntegration().perform_setup()
            assert not ok
            assert "'bgm' command not found" in message


def test_setup_success_message_mentions_reload(fake_home: Path, patched_home):
    fake_bgm = _make_bgm(fake_home)
    with patched_home:
        with mock.patch("shutil.which", return_value=str(fake_bgm)):
            ok, message = PiIntegration().perform_setup()
            assert ok
            assert "/reload" in message


def test_registry_returns_pi():
    integration = IntegrationRegistry.get_integration_by_id("pi")
    assert isinstance(integration, PiIntegration)


def test_registry_order_pi_after_dsh():
    ids = [
        integration.get_tool_info()[0] for integration in IntegrationRegistry.get_all_integrations()
    ]
    assert ids.index("pi") == ids.index("dsh") + 1
