#!/usr/bin/env python3
"""
DeepSeek Harness (dsh) integration for AI BGM.

DeepSeek Harness is a desktop GUI app whose web profile (``~/.dsh/profiles/web``)
loads Cordis plugins resolved from the profile's ``node_modules`` directory. BGM
hooks in by generating a small ESM plugin package (``mythril-agent-bgm-dsh``)
plus an ``- insert:`` entry in the profile's ``cordis.patch.yml``, which the
profile loader applies as a plugin-row insert.

The plugin subscribes to dsh session/agent events (``agent/status``,
``session/event``, ``session/disposed``) and spawns the ``bgm`` CLI as a
detached child process. Patch-file edits are plain string operations (no YAML
dependency), and the generated plugin swallows all spawn errors so an
unavailable ``bgm`` can never break a dsh session.

Patch-file note: dsh scaffolds ``cordis.patch.yml`` with a bare ``[]``
(empty-array placeholder) line. A block-sequence entry appended after it is
invalid YAML — dsh parses patch files with a fail-loud policy, so the profile
would refuse to boot. Appending therefore drops that placeholder, and cleanup
restores it when no entries are left (a comment-only file parses as ``null``,
which dsh also rejects as "must be a top-level YAML array").
"""

import json
import re
import shutil
from pathlib import Path
from typing import Tuple

from mythril_agent_bgm.commands.integrations import AIToolIntegration

# Cordis plugin id; must match the `- id:` row inserted into cordis.patch.yml.
_PLUGIN_ID = "mythril-agent-bgm"
# npm package name of the generated plugin inside the profile's node_modules.
_PACKAGE_NAME = "mythril-agent-bgm-dsh"
# Default target profile: the GUI profile.
_PROFILE = "web"

# Plugin JS template. `__PLUGIN_ID__` and `__BGM_PATH_JSON__` are replaced at
# generation time (json-escaped so paths with quotes/backslashes stay valid).
_PLUGIN_TEMPLATE = """\
// Auto-generated by AI BGM (https://github.com/anthropics/mythril-agent-bgm)
// Re-run `bgm setup` to regenerate.

import { spawn } from "node:child_process";

export const name = "__PLUGIN_ID__";

// Cordis service injection: `session/event` callbacks dispatch on the
// session-scoped carrier, whose fiber chain does NOT resolve `ctx.agents`
// (agent/status callbacks dispatch on the agent carrier and do). Declaring
// the dependency binds the service on this plugin's context so both paths
// can use it — without this, `ctx.agents` throws "cannot get property
// 'agents' without inject" inside the session/event handler.
export const inject = ["agents"];

const BGM = __BGM_PATH_JSON__;

export function apply(ctx) {
  // Root agents that are currently running (drives the "done" cue only).
  const runningRoots = new Set();

  // Call ids of ask_user_question tools still awaiting the user's answer;
  // their tool/result resumes work music (the answer is not a user/message).
  const pendingQuestions = new Set();

  // Work music starts on a real user prompt, not on session/agent startup.
  // Debounce guards against synthetic user/message bursts.
  const DEBOUNCE_MS = 2000;
  let lastWorkTime = 0;

  const run = (...args) => {
    const child = spawn(BGM, args, {
      stdio: "ignore",
      detached: true,
      windowsHide: true,
    });
    // bgm must never break a dsh session: swallow async spawn failures
    // (e.g. ENOENT when the embedded bgm path is stale).
    child.on("error", () => {});
    child.unref();
  };

  const isRootSession = (session) => {
    const roots = ctx.agents?.roots?.() ?? [];
    return roots.some((agent) => agent.session?.id === session?.id);
  };

  ctx.on(
    "agent/status",
    ({ agent, status }) => {
      // Only root agents drive BGM; subagent churn must not restart tracks.
      const roots = ctx.agents?.roots?.() ?? [];
      if (!roots.includes(agent)) return;
      if (status === "running") {
        runningRoots.add(agent);
      } else if (status === "idle") {
        runningRoots.delete(agent);
        // Last root agent idle -> bgm play done. Gated on work music
        // actually having played this session: a running->idle transition
        // with no prior user/message (e.g. resumed session auto-runs on a
        // pending inbox) must not fire a done cue.
        if (runningRoots.size === 0 && lastWorkTime > 0) run("play", "done");
      }
    },
    { global: true }
  );

  ctx.on(
    "session/event",
    (session, event) => {
      if (event?.type === "user/message") {
        // A real user prompt: start (or restart, e.g. after a manual
        // `bgm stop`) the work loop.
        const now = Date.now();
        if (isRootSession(session) && now - lastWorkTime > DEBOUNCE_MS) {
          lastWorkTime = now;
          run("play", "work", "0");
        }
      } else if (
        event?.type === "tool/call" &&
        event.data?.name === "ask_user_question"
      ) {
        // Agent is waiting on the user -> bgm play notification 0. Reset
        // lastWorkTime so the user's immediate reply (a user/message inside
        // DEBOUNCE_MS) restarts work music instead of being swallowed by the
        // debounce window.
        pendingQuestions.add(event.data.callId);
        lastWorkTime = 0;
        run("play", "notification", "0");
      } else if (event?.type === "tool/result") {
        // The user's answer to a question arrives as a tool/result, not a
        // user/message: resume work music so the notification does not loop
        // until the next prompt.
        const callId = event.data?.message?.source?.callId;
        if (callId !== void 0 && pendingQuestions.delete(callId)) {
          const now = Date.now();
          lastWorkTime = now;
          run("play", "work", "0");
        }
      }
    },
    { global: true }
  );

  ctx.on(
    "session/disposed",
    () => {
      // Forget stale bookkeeping so the next session's first user prompt
      // triggers a fresh `bgm play work 0`.
      runningRoots.clear();
      pendingQuestions.clear();
      lastWorkTime = 0;
      run("stop");
    },
    { global: true }
  );
}
"""

# package.json for the generated plugin package (ESM; loader resolves the
# package name from the profile's node_modules).
_PACKAGE_JSON = (
    "{\n"
    '  "name": "mythril-agent-bgm-dsh",\n'
    '  "version": "1.0.0",\n'
    '  "private": true,\n'
    '  "type": "module",\n'
    '  "main": "index.js",\n'
    '  "exports": { ".": "./index.js" }\n'
    "}\n"
)

# The `- insert:` entry appended to the profile's cordis.patch.yml. Format
# matches dsh-base's cordis.patch.yml (top-level list item, 2-space indented
# children).
_PATCH_ENTRY = "- insert:\n" "    - id: mythril-agent-bgm\n" "      name: mythril-agent-bgm-dsh\n"

# Matches one top-level `- insert:` block: the header line plus its indented
# child lines. Blank lines (and the next top-level entry) end the block.
_PATCH_BLOCK_RE = re.compile(r"^- insert:(?:\r?\n[ \t][^\r\n]*)*", re.MULTILINE)

# Matches dsh's empty-array placeholder: a bare `[]` on its own top-level
# line (column 0, so nested `config: []` values are never touched).
_EMPTY_PATCH_RE = re.compile(r"^\[\][ \t]*(?:\r?\n)?", re.MULTILINE)


class _PatchFileError(Exception):
    """The profile's cordis.patch.yml could not be read or written."""


class DshIntegration(AIToolIntegration):
    """Integration for DeepSeek Harness via a Cordis plugin package."""

    def get_tool_info(self) -> Tuple[str, str]:
        """Get DeepSeek Harness tool information."""
        return ("dsh", "DeepSeek Harness")

    def get_settings_path(self) -> Path:
        """Get the generated plugin entry file path (index.js)."""
        return (
            Path.home()
            / ".dsh"
            / "profiles"
            / _PROFILE
            / "node_modules"
            / _PACKAGE_NAME
            / "index.js"
        )

    def get_config_dir(self) -> Path:
        """dsh config root used to detect whether dsh is installed."""
        return Path.home() / ".dsh"

    def setup_hooks(self, settings: dict) -> dict:
        """Not used (plugin-based setup). Returns settings unchanged."""
        return settings

    def cleanup_hooks(self, settings: dict) -> dict:
        """Not used (plugin-based cleanup). Returns settings unchanged."""
        return settings

    def is_configured(self) -> bool:
        """BGM is configured iff the plugin package exists and the patch entry is present."""
        if not self._get_package_dir().exists():
            return False
        patch_path = self._get_patch_path()
        if not patch_path.exists():
            return False
        try:
            content = patch_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            return False
        return self._patch_entry_exists(content)

    def is_up_to_date(self) -> bool:
        """BGM is up to date iff plugin files match generated content and the patch entry exists."""
        bgm_path = shutil.which("bgm")
        if not bgm_path:
            return False
        package_dir = self._get_package_dir()
        index_path = package_dir / "index.js"
        package_json_path = package_dir / "package.json"
        if not index_path.exists() or not package_json_path.exists():
            return False
        try:
            index_matches = index_path.read_text(encoding="utf-8") == self._generate_plugin(
                bgm_path
            )
            package_matches = (
                package_json_path.read_text(encoding="utf-8") == self._generate_package_json()
            )
        except (OSError, UnicodeDecodeError):
            return False
        if not index_matches or not package_matches:
            return False
        patch_path = self._get_patch_path()
        if not patch_path.exists():
            return False
        try:
            patch_content = patch_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            return False
        return self._patch_entry_exists(patch_content)

    def perform_setup(self) -> Tuple[bool, str]:
        """Write the BGM plugin package and patch entry into the web profile."""
        config_dir = self.get_config_dir()
        profile_dir = self._get_profile_dir()
        if not config_dir.exists() or not profile_dir.exists():
            return (
                False,
                f"DeepSeek Harness: Profile directory not found (~/.dsh/profiles/{_PROFILE}) — "
                f"run `dsh {_PROFILE}` once to initialize",
            )

        bgm_path = shutil.which("bgm")
        if not bgm_path:
            return (False, "DeepSeek Harness: 'bgm' command not found in PATH")

        package_dir = self._get_package_dir()
        try:
            package_dir.mkdir(parents=True, exist_ok=True)
            (package_dir / "index.js").write_text(self._generate_plugin(bgm_path), encoding="utf-8")
            (package_dir / "package.json").write_text(
                self._generate_package_json(), encoding="utf-8"
            )
        except (OSError, UnicodeDecodeError) as exc:
            return (False, f"DeepSeek Harness: Unable to write plugin package: {exc}")

        try:
            self._append_patch_entry()
        except _PatchFileError as exc:
            return (
                False,
                f"DeepSeek Harness: Unable to read cordis.patch.yml: {exc}",
            )
        return (
            True,
            f"DeepSeek Harness: Plugin installed successfully [OK] — please restart dsh {_PROFILE} to activate",
        )

    def perform_cleanup(self) -> Tuple[bool, str]:
        """Remove the BGM plugin package and its patch entry."""
        removed = False
        package_dir = self._get_package_dir()
        if package_dir.exists():
            if package_dir.is_symlink():
                package_dir.unlink()
            else:
                shutil.rmtree(package_dir)
            removed = True
        try:
            patch_removed = self._remove_patch_entry()
        except _PatchFileError as exc:
            return (
                False,
                f"DeepSeek Harness: Unable to read cordis.patch.yml: {exc}",
            )
        if patch_removed:
            removed = True
        if not removed:
            return (True, "DeepSeek Harness: No plugin found, nothing to clean up")
        return (True, "DeepSeek Harness: Plugin removed successfully [OK]")

    def _get_profile_dir(self) -> Path:
        """Target dsh profile directory (default: the GUI/web profile)."""
        return Path.home() / ".dsh" / "profiles" / _PROFILE

    def _get_package_dir(self) -> Path:
        """Directory holding the generated plugin package."""
        return self.get_settings_path().parent

    def _get_patch_path(self) -> Path:
        """cordis.patch.yml of the target profile."""
        return self._get_profile_dir() / "cordis.patch.yml"

    @staticmethod
    def _generate_plugin(bgm_path: str) -> str:
        """Generate the plugin JS content with the resolved bgm path embedded."""
        plugin = _PLUGIN_TEMPLATE.replace("__PLUGIN_ID__", _PLUGIN_ID)
        return plugin.replace("__BGM_PATH_JSON__", json.dumps(bgm_path))

    @staticmethod
    def _generate_package_json() -> str:
        """Generate the plugin package.json content."""
        return _PACKAGE_JSON

    @staticmethod
    def _patch_entry_exists(content: str) -> bool:
        """True iff the patch content already contains the BGM insert id line."""
        return any(line.strip() == "- id: mythril-agent-bgm" for line in content.splitlines())

    @staticmethod
    def _append_patch_entry_to_content(content: str) -> str:
        """Return ``content`` with the BGM insert entry appended.

        dsh's scaffolded empty-array placeholder (``[]``) is dropped first:
        it cannot coexist with the appended block-sequence entry. The appended
        entry uses the file's existing line-ending style (CRLF when the
        content contains ``\\r\\n``, LF otherwise) so the file's style is
        preserved; every other pre-existing byte is untouched.
        """
        content = DshIntegration._strip_empty_placeholder(content)
        eol = "\r\n" if "\r\n" in content else "\n"
        if content and not content.endswith("\n"):
            content += eol
        return content + _PATCH_ENTRY.replace("\n", eol)

    @staticmethod
    def _strip_empty_placeholder(content: str) -> str:
        """Remove dsh's top-level ``[]`` empty-array placeholder.

        A file containing both ``[]`` and any ``- `` entry is invalid YAML,
        and dsh fails loud on an unparsable patch layer, so the placeholder
        must never survive alongside an entry. Nested empty arrays (indented,
        e.g. ``config: []``) are left alone.
        """
        return _EMPTY_PATCH_RE.sub("", content)

    @staticmethod
    def _restore_empty_placeholder(content: str) -> str:
        """Re-add dsh's ``[]`` placeholder when no top-level entry is left.

        Comment-only content parses as ``null``, which dsh rejects ("must be
        a top-level YAML array"), so a patch file that still exists after our
        entry is removed needs the placeholder back. Content that already has
        an entry (or is empty — the caller deletes such a file) is returned
        unchanged.
        """
        if not content.strip():
            return content
        if any(line.startswith("- ") for line in content.splitlines()):
            return content
        eol = "\r\n" if "\r\n" in content else "\n"
        if not content.endswith(("\n", "\r")):
            content += eol
        return content + "[]" + eol

    @staticmethod
    def _strip_patch_entry(content: str) -> str:
        """Remove the BGM ``- insert:`` block from ``content``.

        Only the block whose children contain exactly the BGM id line is
        removed (a ``mythril-agent-bgm-legacy``-style prefix id is left
        alone). Blank lines left behind by the removal are collapsed so the
        file stays tidy, and when the block sat at the end of the file the
        trailing line ending (LF or CRLF) matches the file's style; every
        other byte is preserved.
        """
        for match in _PATCH_BLOCK_RE.finditer(content):
            block = match.group(0)
            if not any(line.strip() == f"- id: {_PLUGIN_ID}" for line in block.splitlines()):
                continue
            start, end = match.start(), match.end()
            # Consume the block's own trailing line ending and any blank
            # lines that immediately followed it (they only separated this
            # entry). Handles both LF ("\n") and CRLF ("\r\n") endings.
            while end < len(content) and content[end] in ("\r", "\n"):
                end += 1
            if end < len(content):
                # The block sat in the middle of the file: something follows
                # it, so every remaining byte (including blank lines the
                # tail itself ends with at EOF) must be preserved as-is.
                return DshIntegration._restore_empty_placeholder(
                    content[:start] + content[end:]
                )
            result = content[:start]
            # The block sat at the end of the file: drop a leftover trailing
            # blank line so the file ends with a single line ending, keeping
            # the file's own style (identity when nothing extra remains).
            eol = "\r\n" if "\r\n" in content else "\n"
            return DshIntegration._restore_empty_placeholder(
                re.sub(r"(?:\r?\n)+$", eol, result)
            )
        return content

    def _append_patch_entry(self) -> bool:
        """Append the BGM insert entry to cordis.patch.yml (idempotent).

        Also repairs a file left invalid by an older setup: dsh's scaffolded
        ``[]`` placeholder is dropped even when our entry is already present,
        because a placeholder plus any entry is unparsable and dsh fails loud
        on it. Returns True when the file was modified, False when it was
        already correct. Raises ``_PatchFileError`` if the patch file cannot
        be read or written.
        """
        patch_path = self._get_patch_path()
        try:
            content = patch_path.read_text(encoding="utf-8") if patch_path.exists() else ""
        except (OSError, UnicodeDecodeError) as exc:
            raise _PatchFileError(str(exc)) from exc
        if self._patch_entry_exists(content):
            new_content = self._strip_empty_placeholder(content)
        else:
            new_content = self._append_patch_entry_to_content(content)
        if new_content == content:
            return False
        try:
            patch_path.write_text(new_content, encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            raise _PatchFileError(str(exc)) from exc
        return True

    def _remove_patch_entry(self) -> bool:
        """Remove the BGM insert entry from cordis.patch.yml, preserving the rest byte-for-byte.

        Returns True when the entry was removed, False when there was nothing
        to remove. Raises ``_PatchFileError`` if the patch file cannot be read
        or written.
        """
        patch_path = self._get_patch_path()
        if not patch_path.exists():
            return False
        try:
            content = patch_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            raise _PatchFileError(str(exc)) from exc
        new_content = self._strip_patch_entry(content)
        if new_content == content:
            return False
        try:
            if new_content:
                patch_path.write_text(new_content, encoding="utf-8")
            else:
                # The patch file only contained our entry; drop it entirely so
                # cleanup fully restores the pre-setup state.
                patch_path.unlink()
        except (OSError, UnicodeDecodeError) as exc:
            raise _PatchFileError(str(exc)) from exc
        return True
