#!/usr/bin/env python3
"""
OpenCode integration for AI BGM.

OpenCode does not support declarative lifecycle hooks in its config.
Instead, it provides a plugin system (JS/TS modules) that can subscribe
to events. This integration generates a lightweight JS plugin file.
"""

import json
import shutil
from pathlib import Path
from typing import Tuple

from mythril_agent_bgm.commands.integrations import AIToolIntegration

# OpenCode 2.x validates every plugin module against a schema that requires the
# module's default export to be an object shaped like { id, setup } (or
# { id, effect }). The 1.x form — default-exporting an async function that
# returns a hooks object — is rejected at load time with:
#   Plugin must export a default definition with an id and an effect or setup
#   function.
# See https://opencode.ai/docs/plugins/ and packages/core/src/plugin/module.ts
# in the opencode repository.
#
# __BGM_PATH__ is replaced with the resolved path to the bgm executable.
_PLUGIN_TEMPLATE = r"""// Auto-generated by AI BGM (https://github.com/anthropics/mythril-agent-bgm)
// Re-run `bgm setup` to regenerate.

import { spawn as spawnChild } from "node:child_process";

export const BGMPlugin = {
  id: "bgm",
  setup: async (ctx) => {
    let mainSessionID = null;
    let isWorking = false;
    let lastIdleTime = 0;
    let isWaitingInput = false;

    const DEBOUNCE_MS = 2000;
    const BGM = __BGM_PATH__;

    // OpenCode keeps one plugin instance per open location and broadcasts every
    // event to all of them, so an instance must only react to sessions that
    // live in its own directory. Otherwise every instance would restart the
    // music and they would fight each other.
    const HERE = ctx?.location?.directory ?? null;

    const runBgm = (...args) => {
      try {
        if (typeof Bun !== "undefined" && typeof Bun.spawn === "function") {
          Bun.spawn([BGM, ...args], { stdout: "ignore", stderr: "ignore", env: process.env });
          return;
        }
        const child = spawnChild(BGM, args, { stdio: "ignore", detached: true, env: process.env });
        child.on("error", () => {});
        child.unref();
      } catch (_error) {
        // Music must never break the agent.
      }
    };

    const belongsHere = (event) => {
      // The location lives on the event itself; only a few payloads (such as
      // session.created) repeat it inside data.
      const directory = event?.location?.directory ?? event?.data?.location?.directory ?? null;
      return directory === null || HERE === null || directory === HERE;
    };

    const startWork = () => {
      if (isWorking) return;
      isWaitingInput = false;
      isWorking = true;
      runBgm("play", "work", "0");
    };

    const finishWork = () => {
      if (!isWorking) return;
      isWorking = false;
      lastIdleTime = Date.now();
      runBgm("play", "done");
    };

    const askForInput = () => {
      isWaitingInput = true;
      isWorking = false;
      runBgm("play", "notification", "0");
    };

    const onEvent = (event) => {
      // 2.x events are flat: { type, data }. The 1.x shape was
      // { type, properties }, which is why reading properties silently
      // produced undefined instead of failing.
      const type = event?.type;
      const data = event?.data ?? {};

      // Ignore sessions owned by another location's plugin instance.
      if (!belongsHere(event)) return;

      if (type === "session.created") {
        // Subagent sessions carry parentID; only the main one drives the music.
        if (data.parentID || mainSessionID !== null) return;
        mainSessionID = data.sessionID ?? null;
        isWorking = false;
        lastIdleTime = 0;
        isWaitingInput = false;
        return;
      }

      if (mainSessionID === null) {
        // session.created can be missed when the plugin loads after the
        // session starts. Adopt the first user prompt that belongs here.
        if (type !== "session.inbox.enqueued" || data?.item?.type !== "user") return;
        mainSessionID = data.sessionID ?? null;
      }

      if (data.sessionID !== undefined && data.sessionID !== mainSessionID) return;

      switch (type) {
        case "session.inbox.enqueued":
          // A run can queue several user/synthetic items; the debounce keeps
          // the work track from reshuffling on every one of them.
          if (
            !isWorking &&
            data?.item?.type === "user" &&
            Date.now() - lastIdleTime > DEBOUNCE_MS
          ) {
            startWork();
          }
          break;

        case "session.execution.started":
          startWork();
          break;

        case "permission.asked":
        case "form.created":
          askForInput();
          break;

        case "permission.replied":
        case "form.replied":
          if (isWaitingInput) startWork();
          break;

        case "session.status":
          if (data?.status?.type === "busy") startWork();
          else if (data?.status?.type === "idle") finishWork();
          break;

        case "session.idle":
        case "session.execution.succeeded":
        case "session.execution.failed":
        case "session.execution.interrupted":
          finishWork();
          break;

        case "session.deleted":
          isWorking = false;
          isWaitingInput = false;
          mainSessionID = null;
          runBgm("stop");
          break;
      }
    };

    const controller = new AbortController();

    const listen = async () => {
      while (!controller.signal.aborted) {
        try {
          const stream = ctx.event.subscribe({ signal: controller.signal });
          const iterable = typeof stream?.then === "function" ? await stream : stream;
          for await (const event of iterable) {
            if (controller.signal.aborted) return;
            try {
              onEvent(event);
            } catch (_error) {
              /* one bad event must not kill the subscription */
            }
          }
        } catch (_error) {
          if (controller.signal.aborted) return;
        }
        await new Promise((resolve) => setTimeout(resolve, 1000));
      }
    };

    void listen();

    // OpenCode awaits this cleanup when the plugin is unloaded or replaced.
    return () => {
      controller.abort();
    };
  },
};

export default BGMPlugin;
"""


class OpenCodeIntegration(AIToolIntegration):
    """Integration for OpenCode via plugin file."""

    def get_tool_info(self) -> Tuple[str, str]:
        """Get OpenCode tool information."""
        return ("opencode", "OpenCode")

    def get_settings_path(self) -> Path:
        """Get the plugin file path."""
        return Path.home() / ".config" / "opencode" / "plugins" / "opencode-bgm.js"

    def get_config_dir(self) -> Path:
        """OpenCode config root is ~/.config/opencode/, not the plugins/ subdirectory."""
        return Path.home() / ".config" / "opencode"

    def setup_hooks(self, settings: dict) -> dict:
        """Not used for OpenCode (plugin-based setup). Returns settings unchanged."""
        return settings

    def cleanup_hooks(self, settings: dict) -> dict:
        """Not used for OpenCode (plugin-based cleanup). Returns settings unchanged."""
        return settings

    def is_configured(self) -> bool:
        """BGM is configured iff the plugin file exists (regardless of content)."""
        return self.get_settings_path().exists()

    def is_up_to_date(self) -> bool:
        """BGM is up to date iff the plugin file exists with the current expected content."""
        plugin_path = self.get_settings_path()
        if not plugin_path.exists():
            return False
        bgm_path = shutil.which("bgm")
        if not bgm_path:
            return False
        expected = self._generate_plugin(bgm_path)
        return plugin_path.read_text(encoding="utf-8") == expected

    def perform_setup(self) -> Tuple[bool, str]:
        """Write the BGM plugin JS file into OpenCode's plugin directory."""
        config_dir = self.get_config_dir()
        if not config_dir.exists():
            return (False, f"OpenCode: Config directory not found ({config_dir})")

        bgm_path = shutil.which("bgm")
        if not bgm_path:
            return (False, "OpenCode: 'bgm' command not found in PATH")

        plugin_dir = self.get_settings_path().parent
        plugin_dir.mkdir(parents=True, exist_ok=True)

        plugin_content = self._generate_plugin(bgm_path)
        self.get_settings_path().write_text(plugin_content, encoding="utf-8")
        return (True, "OpenCode: Plugin installed successfully [OK]")

    def perform_cleanup(self) -> Tuple[bool, str]:
        """Remove the BGM plugin JS file from OpenCode's plugin directory."""
        plugin_path = self.get_settings_path()
        if not plugin_path.exists():
            return (True, "OpenCode: No plugin file found, nothing to clean up")

        plugin_path.unlink()
        return (True, "OpenCode: Plugin removed successfully [OK]")

    @staticmethod
    def _generate_plugin(bgm_path: str) -> str:
        """Render the OpenCode 2.x plugin file for the given bgm executable.

        The path is JSON-encoded so that Windows separators (C:\\Users\\...)
        survive as a valid JavaScript string literal.

        Uses Bun.spawn instead of Bun's $ template literal because $ misparses
        compound command strings (e.g. "$`${path} play work 0`" passes
        incorrect arguments to the subprocess).
        """
        return _PLUGIN_TEMPLATE.replace("__BGM_PATH__", json.dumps(bgm_path))
